### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by dexter101010** [wisebobo/m3u8_Downloader#1]
Hello team, 

I have the following problem with your script : 

Invalid URL 'k/timestamp': No schema supplied. Perhaps you meant http://k/timestamp?

https://vcdn.spayee.in/spees/w/o/5b49b8f2e4b02ac9d5e71945/v/5cb05002e4b00db56cfb383a/u/5cd933e1e4b0c2b0f7965a3b/t/fbd49f133067d227c1aee127d1c1a691/p/assets/videos/2019/04/12/5cb05002e4b00db56cfb383a/hls_1M_.m3u8

Best regards!

**Comment by wisebobo** [comment]
Hi Dexter,

Checked your m3u8 file and found that could be due to your m3u8 file data issue, as the URI is setting as "k/timestamp" only.

Maybe your specific website has its own logic to resolve this URI, which is unknown to us.

`#EXT-X-KEY:METHOD=AES-128,URI="k/timestamp",IV=0x496daa1c6914000e408c65cead91fc29`
